version: '3.8'

services:
  frontend:
    image: ${DOCKER_REGISTRY}/hotel-tracker-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=https://api.hoteltracker.com
      - NODE_ENV=production
    networks:
      - hotel-network

  backend:
    image: ${DOCKER_REGISTRY}/hotel-tracker-backend:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
    depends_on:
      - db
    networks:
      - hotel-network

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - hotel-network

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - hotel-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www
    depends_on:
      - frontend
      - backend
    networks:
      - hotel-network

volumes:
  postgres_data:
  redis_data:

networks:
  hotel-network:
    driver: bridge
