services:
  - type: web
    name: hotel-tracker-api
    env: python
    buildCommand: |
      python -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      python server.py
    region: ohio
    plan: starter
    healthCheckPath: /health
    port: 10000
    domains:
      - hoteltracker.org
      - api.hoteltracker.org
      - www.hoteltracker.org
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: INTERNAL_DATABASE_URL
        fromDatabase:
          name: hotel-tracker-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,hoteltracker.org,api.hoteltracker.org,www.hoteltracker.org"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONPATH
        value: "."
    autoDeploy: true
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: redirect
        source: http://*
        destination: https://$HOST
        status: 301

  - type: web
    name: hotel-tracker-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npm run preview
    region: ohio
    plan: starter
    healthCheckPath: /
    port: 3000
    domains:
      - app.hoteltracker.org
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: VITE_API_URL
        value: https://api.hoteltracker.org
    autoDeploy: true
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff

  - type: redis
    name: hotel-tracker-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

  - type: pserv
    name: hotel-tracker-db
    region: ohio
    plan: starter
    ipAllowList: []
    postgresMajorVersion: 15

databases:
  - name: hotel-tracker-db
    databaseName: hotel_tracker
    plan: starter
    ipAllowList: [] # allow all
