services:
  - type: web
    name: hotel-tracker-web
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-tracker-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: hotel-tracker-redis
          type: redis
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    healthCheckPath: /health
    autoDeploy: true

  - type: worker
    name: hotel-tracker-celery
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-tracker-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: hotel-tracker-redis
          type: redis
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    command: celery -A backend.tasks.celery worker --loglevel=info

databases:
  - name: hotel-tracker-db
    databaseName: hotel_tracker
    plan: starter
    ipAllowList: [] # allow all

redis:
  - name: hotel-tracker-redis
    plan: free
    maxmemoryPolicy: noeviction
