services:
  - type: web
    name: hotel-tracker-api
    env: docker
    region: ohio
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    port: 10000
    domains:
      - hoteltracker.org
      - api.hoteltracker.org
      - www.hoteltracker.org
    envVars:
      - key: PORT
        value: 10000
      - key: INTERNAL_DATABASE_URL
        sync: false
      - key: EXTERNAL_DATABASE_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,hoteltracker.org,api.hoteltracker.org,www.hoteltracker.org"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    autoDeploy: true
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: redirect
        source: http://*
        destination: https://$HOST
        status: 301

  - type: redis
    name: hotel-tracker-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

databases:
  - name: hotel-tracker-db
    databaseName: hotel_tracker
    plan: starter
    ipAllowList: [] # allow all
