services:
  - type: web
    name: hotel-tracker-api
    env: python
    buildCommand: |
      python -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      python server.py
    region: ohio
    plan: starter
    healthCheckPath: /health
    port: 10000
    domains:
      - hoteltracker.org
      - api.hoteltracker.org
      - www.hoteltracker.org
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: INTERNAL_DATABASE_URL
        sync: false
      - key: EXTERNAL_DATABASE_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,hoteltracker.org,api.hoteltracker.org,www.hoteltracker.org"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONPATH
        value: "."
    autoDeploy: true
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: redirect
        source: http://*
        destination: https://$HOST
        status: 301

  - type: web
    name: hotel-tracker-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    domains:
      - app.hoteltracker.org
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: redirect
        source: /api/*
        destination: https://api.hoteltracker.org/*
        status: 301
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://api.hoteltracker.org
      - key: NODE_VERSION
        value: 18.17.0

  - type: redis
    name: hotel-tracker-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

databases:
  - name: hotel-tracker-db
    databaseName: hotel_tracker
    plan: starter
    ipAllowList: [] # allow all
